# -*- coding: utf-8 -*-
"""VR Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hkiSSgSTllffEoorQ_2L1Unb5W1_dYoX
"""

from google.colab import drive
drive.mount('/content/gdrive')

!ls -l gdrive/My\ Drive/dataset/shirt/

import os
os.listdir("gdrive/My Drive/dataset")



file = open("test.txt", "w")
path = "gdrive/My Drive/dataset/"
for img in os.listdir(path+"shirt"):
  file.write("../"+path+"shirt"+"/"+img+"\n")
for img in os.listdir(path+"saree"):
  file.write("../"+path+"saree"+"/"+img+"\n")
file.close()

!wc -l new_test.txt

!cp new_test.txt gdrive/My\ Drive/

# make sure you use Tesla K80 GPU (12GB), by changing 'runtmie type' 

!nvidia-smi

#clone darknet repository 
import os
os.environ['PATH'] += ':/usr/local/cuda/bin'
!rm -fr darknet
!git clone https://github.com/AlexeyAB/darknet/

!apt install gcc-5 g++-5 -y
!ln -s /usr/bin/gcc-5 /usr/local/cuda/bin/gcc 
!ln -s /usr/bin/g++-5 /usr/local/cuda/bin/g++

# Commented out IPython magic to ensure Python compatibility.
# go to the darknet folder, enable GPU, then compile the entire thing
# %cd darknet
!sed -i 's/GPU=0/GPU=1/g' Makefile
!sed -i 's/OPENCV=0/OPENCV=1/g' Makefile
!make

# get yolov3 weights
!wget https://pjreddie.com/media/files/yolov3.weights
!chmod a+x ./darknet

!pwd

!apt install ffmpeg libopencv-dev libgtk-3-dev python-numpy python3-numpy libdc1394-22 libdc1394-22-dev libjpeg-dev libtiff5-dev libavcodec-dev libavformat-dev libswscale-dev libxine2-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libv4l-dev libtbb-dev qtbase5-dev libfaac-dev libmp3lame-dev libopencore-amrnb-dev libopencore-amrwb-dev libtheora-dev libvorbis-dev libxvidcore-dev x264 v4l-utils unzip

!ls ../

!./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights -dont_show -ext_output < ../gdrive/My\ Drive/new_test.txt > new_result.txt

!cp new_result.txt ../gdrive/My\ Drive/

!ls -l

!./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights -dont_show -ext_output ../gdrive/My\ Drive/dataset/other/0000002774_h.png

import cv2
import matplotlib.pyplot as plt
import os.path

fig,ax = plt.subplots()
ax.tick_params(labelbottom="off",bottom="off")
ax.tick_params(labelleft="off",left="off")
ax.set_xticklabels([]) 
ax.axis('off')

file = './predictions.jpg'
if os.path.exists(file):
  img = cv2.imread(file)
  show_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) 
  plt.imshow(show_img)